# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]    
    paths:
      - Bicep/**
  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      rg_name: RgChallenge3
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.0
        with:
          # Bicep main file path
          bicepFilePath: ./Bicep/main.bicep
          # ARM template output path
          outputFilePath: ./ARMazuredeploy.json
      - uses: actions/upload-artifact@v2
        with:
          name: ARM
          path: ./ARMazuredeploy.json
      - uses: Azure/login@v1.1
        with:
          creds: '{"clientId":"${{ secrets.APPID }}","clientSecret":"${{ secrets.PASSWORD }}","subscriptionId":"${{ secrets.SUBSCRIPTION }}","tenantId":"${{ secrets.TENANT }}"}'
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:          
          scope: 'resourcegroup'                             
          resourceGroupName: ${{ env.rg_name }}
          # Specify the path or URL to the Azure Resource Manager template.
          template:  ./ARMazuredeploy.json
          deploymentMode: Incremental         
